version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devcontainer
    volumes:
      - .:/workspace
    depends_on:
      - db
    command: sleep infinity

volumes:
  db_data:
