version: "3.8"
services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  dev:
    build: .
    volumes:
      - .:/workspace
    ports:
      - "5585:5585"
    depends_on:
      - db
    command: sleep infinity

volumes:
  db_data:
